### ISSUE TITLE
images for readme

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics-Bokeh#1]
![dvh_screen-shot](https://cloud.githubusercontent.com/assets/4778878/26416076/49c71180-407a-11e7-9e21-83ea29eec739.png)

**Comment by cutright** [comment]
![image](https://cloud.githubusercontent.com/assets/4778878/26684304/2fde4558-46ac-11e7-81ad-15dda1122ecd.png)

**Comment by cutright** [comment]
![image](https://cloud.githubusercontent.com/assets/4778878/26684430/99fc183e-46ac-11e7-9e41-b768141212d5.png)

**Comment by cutright** [comment]
![dvh_analytics_sample_views_web_new](https://user-images.githubusercontent.com/4778878/30643873-2115f6de-9dd6-11e7-9d6c-c51dd8307384.jpg)

**Comment by cutright** [comment]
![githubnew](https://user-images.githubusercontent.com/4778878/30724288-7cabb358-9f02-11e7-83ac-6f600e04ea00.jpg)

**Comment by cutright** [comment]
![logo](https://user-images.githubusercontent.com/4778878/30724445-66fda59c-9f03-11e7-883b-138ecb32a10a.jpg)

**Comment by cutright** [comment]
![logo](https://user-images.githubusercontent.com/4778878/30754005-b7a7e808-9f86-11e7-8b0f-79d1006babdf.jpg)
slight shadow tweak

**Comment by cutright** [comment]
![mlc_analyzer](https://user-images.githubusercontent.com/4778878/37878772-09faa32a-303c-11e8-8732-39346f516ec8.png)
MLC Analyzer module added to DVH Analytics.  Still in development, current complexity score based on:
Younge KC, Matuszak MM, Moran JM, McShan DL, Fraass BA, Roberts DA. Penalization of aperture complexity in inversely planned volumetric modulated arc therapy. Med Phys. 2012;39(11):7160–70.

**Comment by cutright** [comment]
![dvh_analytics_sample_views_web_new_query](https://user-images.githubusercontent.com/4778878/37943568-11f856fc-3146-11e8-85ec-4c0d3cbf2492.png)

**Comment by cutright** [comment]
<img width="1512" alt="DVH_Analytics_Desktop" src="https://user-images.githubusercontent.com/4778878/54063970-01c4eb00-41d6-11e9-95c1-8673773cfb11.png">

**Comment by bastula** [comment]
Looking good! Great work in the revamp. That was fast! 👍

**Comment by cutright** [comment]
<img width="1462" alt="Screen Shot 2019-03-31 at 4 35 37 PM" src="https://user-images.githubusercontent.com/4778878/55295490-473e9780-53d3-11e9-9708-5cfc9276c8d2.png">

Lots of progress! Almost done with a DICOM Importer that will flag studies with important missing tags.  Sorry @bastula , I stole some icons from dicompyler as place holders for now.
