### ISSUE TITLE
another isue

### ISSUE THREAD

**Issue by cat2tom** [cutright/DVH-Analytics-Bokeh#19]
Hi Cutright,

Thanks for quick response. I almost there, but still have issues to run as shown below. By the way, where  the import directories (review, inbox,imported) are created by default?

Thanks,

tom

C:\ProgramData\Anaconda2\lib\site-packages\fuzzywuzzy-0.15.1-py2.7.egg\fuzzywuzzy\fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
Loading create_tables.sql
Executing create_tables.sql
Tables created
True
2017-10-18 13:40:58,976 Starting Bokeh server version 0.12.7 (running on Tornado 4.4.2)
2017-10-18 13:40:58,984 Bokeh app running at: http://localhost:5006/dvh
2017-10-18 13:40:58,984 Starting Bokeh server with process id: 9532
2017-10-18 13:41:04,216 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x0000000008FB8710>: list index out of range
File "main.py", line 496, in __init__:
self.select_value = Select(value=self.values[0], options=self.values, width=420) Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\bokeh\application\handlers\code_runner.py", line 125, in run
    exec(self._code, module.__dict__)
  File "C:\AitangResearch\DVHAnalytics\dvh\main.py", line 3487, in <module>
    button_add_selector_row()
  File "C:\AitangResearch\DVHAnalytics\dvh\main.py", line 220, in button_add_selector_row
    query_row.append(SelectorRow())
  File "C:\AitangResearch\DVHAnalytics\dvh\main.py", line 496, in __init__
    self.select_value = Select(value=self.values[0], options=self.values, width=420)
IndexError: list index out of range
 
2017-10-18 13:41:04,226 200 GET /dvh (::1) 4141.00ms
2017-10-18 13:41:04,430 304 GET /dvh/static/images/logo.jpg (::1) 162.00ms
2017-10-18 13:41:04,555 WebSocket connection opened
2017-10-18 13:41:04,555 ServerConnection created
2017-10-18 13:41:04,585 404 GET /favicon.ico (::1) 0.00ms

**Comment by cat2tom** [comment]
![image](https://user-images.githubusercontent.com/26789914/31702803-1bbb139e-b425-11e7-892f-51eac5553316.png)

**Comment by cutright** [comment]
Hi Tom, thanks for your patience.

Currently, your import settings are empty (i.e., there are no default folders).  So when you run the `$ python start.py settings`, fill in ~~absolute~~ directories. For example, my file looks like:
```
inbox /Users/nightowl/PycharmProjects/dvh-analytics/inbox
imported /Users/nightowl/PycharmProjects/dvh-analytics/imported
review /Users/nightowl/PycharmProjects/dvh-analytics/review
```
In the meantime, I'll add a note in the settings page indicating these are absolute directory paths.  I'll work on a more convenient implementation soon.  Perhaps some javascript can help here to allow the user to select from a file explorer. I'll work on a thoughtful method to create a directory if not found.

For the remaining errors, I suspect your SQL database is empty.  After updating your import settings, I would suggest running `python start.py admin` and import some data.  I'll add some code today to prevent running the main view if there is no data and prompting the user to go to the admin view to import data.

A fair warning, running the main view expects the database manager (you) has already curated the data (if needed). After import, use the admin view to peruse your data to make sure nothing is blank or awry.  You'll also need to run the Calc PTV distances and Calc PTV Overlap functions after import, this assumes you've labeled your PTV though.  Before exporting from your TPS, you can set your ROI type to PTV, or you can edit the ROI type in the Database Editor tab of the admin view.  But this won't stick if you clear your SQL tables and reimport your dicom files (so best to set it in your TPS prior to export).

And make sure that the physician initials in your data are available as a physician in the ROI Name Manager (you may need to click Remap all ROIs in DB after building your ROI Map).

I will get working on an instruction manual soon.  I apologize for the hiccups on your end, but knowing about these types of issues are very helpful to me.

**Comment by cutright** [comment]
I thought I had error catching on the directories...  If you change the value in the input box for directories, it will tell you if it's a valid path or not.  I'll update the code to tell you this at the launch of the view.
<img width="241" alt="directories" src="https://user-images.githubusercontent.com/4778878/31717800-06936d10-b3d3-11e7-827c-3f4f68bd043d.png">

**Comment by cutright** [comment]
Apparently relative directories may work as well (at least on mac and linux).  Just be careful as relative directories are relative to the currently running python script.  I would recommend using absolute directory paths just to be safe.

**Comment by cutright** [comment]
Hi Tom,

I think I've made this process easier with tonight's upload (PyPI version 0.2.21), and updated the installation notes accordingly.

* Running `$ dvh settings` or `$ python start.py settings` will create import_settings.txt and and sql_connection.cfg default files if the files do not exist.
* The invalid path or path needed notes on the settings.py bokeh app update at launch, to avoid confusion

I'm going to close this issue, but let me know if you run into other issues.

Dan
