### ISSUE TITLE
DICOM to Python import assumes Beam Dose Specification Point exists in the RTPLAN file

### ISSUE THREAD

**Issue by keithoffer** [cutright/DVH-Analytics-Bokeh#23]
I noticed trying to import some data I have on hand that the importer assumes that the Beam Dose Specification Point is set in the RTPLAN file. The exact lines of code that handle that are [here](https://github.com/cutright/DVH-Analytics/blob/b94b00cd70377e1602accf7bfebc433917aa80d4/dvh/dicom_to_python.py#L417-L419). As far as I understand, this isn't required by the DICOM [specification](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.8.13.html#sect_C.8.8.13), and as such there is no guarantee this is set (note that I could easily be wrong here as I'm not a DICOM expert). At the moment any RTPLAN files without this attribute will crash the importer. I'm not sure what exactly the point is used for elsewhere in the program for analysis, or what should be stored in the database if the point isn't present.

**Comment by cutright** [comment]
First of all, thank you Keith for the feedback.  I'm really glad to see someone else trying this out.

I will add a clause to catch a missing beam dose spec point, and simply store a null value if not found.  In general, I should probably not assume any DICOM tag is present and then report missing data in a log.

Currently, this tag is not used in any analyses, but it may be of use for non-linac based treatments or perhaps plans with multi isocenters or Rxs (e.g., breast + SCV or VMAT craniospinal with matched beams).  Then again, maybe it'll be useless... honestly, I'm just trying to store anything that is even potentially useful.

**Comment by cutright** [comment]
Fixed [here](https://github.com/cutright/DVH-Analytics/commit/511ab53a39d11e0d1fbfb371d5f10e20ac3895c2#diff-bd1b281936df321e880ac276cda57560)
