### ISSUE TITLE
about installation

### ISSUE THREAD

**Issue by Hsiao-Lau** [cutright/DVH-Analytics-Bokeh#33]
i am very insterseted in it for my reserach,but there are many componennts to install after configuring python 2.7 ,can you describe the simplified installation procedure？thanks

**Comment by cutright** [comment]
Hey there, did you get a chance to take a look at the [install notes](https://github.com/cutright/DVH-Analytics/blob/master/install_notes.md)?

The cliff notes:
* Install the code and python dependencies using `$ pip install dvhanalytics`
* Install a Postgres SQL database and give DVH Analytics login credentials

Depending on your level of experience and computer environment, it might just as simple as that.  But I'm happy to walk you through if you hit any snags.

We're looking to containerize this code with Docker to greatly simplify the install process, but we haven't been able to get that going just yet.

**Comment by Hsiao-Lau** [comment]
Thanks，I have installed the DVH-Analytics package，and there remains geos_c.dll left  to solve ，but it is confused me that  there are not instruction brochure in detail.

**Comment by cutright** [comment]
Perhaps [this](https://github.com/Toblerity/Shapely/issues/343) may help?  It's almost certainly an issue with the Shapely install on Windows.  

I appreciate your patience.  Developing nicely bundled, compiled software for all platforms is a bit challenging.  We hope to make this install process more user friendly in the future.

**Comment by Hsiao-Lau** [comment]
if available,is there detailed instructions about DVH-Analytics

**Comment by cutright** [comment]
Unfortunately, I don't have anything beyond the installation notes.  I do, however, have an accepted manuscript to be published any day now (in the 2nd round of editorial review).  I'll be sure to pass that along when it's ready.

Were you able to get a SQL database going and connected? That's often the most difficult/frustrating part.

**Comment by Hsiao-Lau** [comment]
sql databese has been setup，including new login role and new database，but geo_c.dll remains the same situation(i follwed the website you offer,and  OSGeo4W could not installed via my local network,several  OSGeo4W packages could not download when installing OSGeo4W),so it can not initialize DVH Analytics

**Comment by cutright** [comment]
Are you using Anaconda?  If so, try:
`$ conda install shapely`

If not, I can do some more digging if you let me know which python package you have.

**Comment by bastula** [comment]
Sorry didn't chime in earlier. If you are on Windows the old trusty standby is Christopher Gohlke's wonderful binary packages: https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely
Just download and pip install the version you need.

**Comment by Hsiao-Lau** [comment]
yes，i use anaconga to install shapely,but it failed when initializing DVH Analytics,i will try bastula's instruction

**Comment by jxaflxb** [comment]
Package                            Version
---------------------------------- -----------
backports-abc                      0.5
backports.functools-lru-cache      1.5
backports.shutil-get-terminal-size 1.0.0
backports.shutil-which             3.5.1
bleach                             2.1.3
bokeh                              0.12.10
certifi                            2018.4.16
chardet                            3.0.4
click                              6.7
colorama                           0.3.9
configparser                       3.5.0
cycler                             0.10.0
decorator                          4.3.0
dicompyler-core                    0.5.4
dvh-analytics                      0.3.13
entrypoints                        0.2.3
enum34                             1.1.6
Flask                              1.0.2
freetype-py                        1.2.1
functools32                        3.2.3.post2
future                             0.16.0
futures                            3.2.0
fuzzywuzzy                         0.16.0
geos                               0.2.1
html5lib                           1.0.1
idna                               2.7
ipykernel                          4.8.2
ipython                            5.7.0
ipython-genutils                   0.2.0
ipywidgets                         7.2.1
itsdangerous                       0.24
Jinja2                             2.10
jsonschema                         2.6.0
jupyter                            1.0.0
jupyter-client                     5.2.3
jupyter-console                    5.2.0
jupyter-core                       4.4.0
kiwisolver                         1.0.1
lxml                               4.2.2
MarkupSafe                         1.0
matplotlib                         2.2.2
mistune                            0.8.3
mpmath                             1.0.0
nbconvert                          5.3.1
nbformat                           4.4.0
nose                               1.3.7
notebook                           5.5.0
numpy                              1.14.5+mkl
packaging                          17.1
pandas                             0.23.1
pandocfilters                      1.4.2
pathlib2                           2.3.2
pickleshare                        0.7.4
pip                                10.0.1
prompt-toolkit                     1.0.15
psycopg2                           2.7.5
pydicom                            1.1.0
Pygments                           2.2.0
pyparsing                          2.2.0
python-dateutil                    2.7.3
pytz                               2018.4
pywinpty                           0.5.4
PyYAML                             3.12
pyzmq                              17.0.0
qtconsole                          4.3.1
requests                           2.19.1
scandir                            1.7
scipy                              1.1.0
Send2Trash                         1.5.0
setuptools                         39.0.1
Shapely                            1.6.4.post1
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.11.0
statsmodels                        0.9.0
sympy                              1.1.1
terminado                          0.8.1
testpath                           0.3.1
tornado                            4.4.2
traitlets                          4.3.2
urllib3                            1.23
wcwidth                            0.1.7
web.py                             0.39
webencodings                       0.5.1
Werkzeug                           0.14.1
wheel                              0.31.1
widgetsnbextension                 3.2.1
win-unicode-console                0.5

**Comment by cutright** [comment]
FYI, we have a draft of a manual available now
https://github.com/cutright/DVH-Analytics
