### ISSUE TITLE
Beam MU shift in Eclipse plans

### ISSUE THREAD

**Issue by smihaly** [cutright/DVH-Analytics-Bokeh#54]
Hi

First of all, thank you for this extremely useful tool.
I am tried to feed in Pinnacle and Eclipse treatment plans into the system and strangely experienced a shift in beam MUs at the eclipse plans. I have checked the dcm files and the beam numbers are correct and referencing the correct amount of MUs.  Have you come cross this issue? Is there a compatibility issue with eclipse versions?
We don`t have problems with the Pinnacle plans, those are coming through fine. 

Thank you

**Comment by cutright** [comment]
Hi, thanks for trying the software out.  I don't believe there is a distinction between the TPSs, but I have both Pinnacle and Eclipse in my clinic.  I'll give it another check.

Are the beam MU's correct? Or both the total MU and beam MUs are off?

**Comment by cutright** [comment]
I don't see an issue with our Eclipse (v11).  If you send some screen shots I might be able to help?

**Comment by smihaly** [comment]
Hi,

I attached a screenshot of the beams table in the DB.
The last 3 beams are in question, the number of the beams are correct 
(1,5,6), but only the 5 and 6 are treatment beams. The first one has 
only 2 control points and marked as static beam.
The error is, that the setup beam has the MU value of the CW beam and 
the CW beam has the MU vallue of the CCW beam and finally the CCW beam 
has the monitor unit of the kV beam, which is not even imported.

Thank you for looking into this.

**Comment by cutright** [comment]
I think you'll need to add the screen shots with the GitHub web page.  But this information helps.

**Comment by smihaly** [comment]
![DVHAnalytics](https://user-images.githubusercontent.com/48449961/54158207-4789e980-444a-11e9-84bb-1a5410756d4e.png)

Sorry, here it is.
I hope

**Comment by cutright** [comment]
And presumably this works OK if you don't include setup fields in your export?

I'll do some testing on my end with setup fields.

**Comment by smihaly** [comment]
Well, I think it should work fine without setup fields, as you mentioned this should not depend on the TPS and our Pinnacle plans are imported flawlessly. 
The strange thing is there are 8 beams in that particular plan and apart from the  2 treatment beams only this Setup Field gets imported. Might be because it is the first beam in line?

**Comment by cutright** [comment]
I just checked a plan from Eclipse with setup fields and it worked OK.  But I think I see where the issue is.

DICOM stores MU (i.e., meter set in RTPlan->FractionGroupSequence -> ReferencedBeamSequence) in a different object than the beam geometries (RTPlan->BeamSequence).  And I may not be connecting BeamSequence to ReferencedBeamSequence properly.  I'll dive deeper and get back to you.

**Comment by cutright** [comment]
I've pushed a new version (0.5.7) to PyPi and GitHub.  Do you mind updating and trying again?

I now match the Beam Number (DICOM tag (300a, 00c0)) in the BeamSequence to the Referenced Beam Number in FractionGroupSequence->ReferencedBeamSequence(DICOM tag (300c, 0006)).  I believe this is right way.  Previously I assumed two sequences were in the same order.

Does this sound right @bastula ?

**Comment by bastula** [comment]
Yes, you have it correct now. You must follow the Referenced Beam Number (300c, 0006) to determine which Beam Number (300a, 00c0) it corresponds to from BeamSequence.

**Comment by smihaly** [comment]
We have tried 0.5.7 and it imports beams and MUs in the correct order. I think this issue is resolved.
Thank you very much

**Comment by cutright** [comment]
Awesome, glad it's working now.  Stay tuned, we should have a desktop version of DVHA ready for public release within the next few months.  And it'll use the same SQL DB, making for a seamless transition for you.

Thanks @bastula !
