### ISSUE TITLE
Question about physician ROI remap

### ISSUE THREAD

**Issue by zhang-zeyu** [cutright/DVH-Analytics-Bokeh#55]
Hi,

I found the institutional ROI and physician ROI are all uncategorized after data importing, so I go to the ROI name manager to remap ROIs. But there is a error:

error handling message Message u'EVENT' (revision 1) content: u'{"event_name":"button_click","event_values":{"model_id":"2221"}}': KeyError('',)

I don't know if it is a bug or what, could you please give me some hints? Thanks!

Best,

Zeyu

**Comment by zhang-zeyu** [comment]
I also tried your desktop version, it's amazing. The institutional ROI and physician ROI were already remapped after data importing (remap all rois in DB also works on ROI name manager page), but the data imported is not fit to Bokeh version when applying data analysis on main page.

**Comment by cutright** [comment]
Hi Zeyu, thanks for trying out DVHA.  Sorry you're having some issues.

I don't have the Bokeh version environment set up right now to troubleshoot the error, but I should have some time next week.

Can you elaborate a little more about how the data doesn't fit between versions? Could you provide some screenshots?

**Comment by zhang-zeyu** [comment]
Thank you for your reply.

I imported dicom data into postgre database by desktop version, the institutional ROI and physician ROI were already remapped (but not on bokeh version because all of these ROI are uncategorized), so I went to the bokeh version by connecting this postgre database and I found that the there is a error after query:

error handling message Message u'EVENT' (revision 1) content: u'{"event_name":"button_click","event_values":{"model_id":"2335"}}': TypeError("object of type 'bool' has no len()",)

So the 'Rad Bio, ROI viewer, correlation, regression, MLC' tabs did not show anything.

**Comment by cutright** [comment]
Sorry for the delay, but I think I've solved your issue with DVHA Bokeh v0.5.11. Both GitHub and PyPI have been updated.  There were typos in dvhs.py on lines 318 and 429.

Let me know if that resolves your issue.
